#!/bin/bash

register_alias docker-moby "screen -D -R -S moby ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty"

function docker-clean-all() {
  docker-clean-containers
  docker-clean-volumes
}

function docker-clean-volumes() {
  docker volume rm $(docker volume ls -qf dangling=true)
}

function docker-clean-containers() {
  docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm
}

function docker-shell() {
  docker exec -it $1 /bin/bash
}
