#!/bin/bash

function git-tag-for {
  repo=$(git remote -v 2>/dev/null | head -1 | awk '{ print $2 }')
  for grep in "${@}"; do
    for f in $(git log  --oneline --all --grep="$grep" | awk '{ print $1  }'); do
      git tag --contains $f
    done | sort | uniq -c | sort -s -n -r -k1 | head -1 | awk '{ print "'$grep'\t'$repo'\t" $2 }'
  done 2>/dev/null
}

function git-repo-for() {
  for dir in $(find . -name .git -maxdepth 4); do
    repo=$(dirname $dir)
    pushd $repo >/dev/null
    git-tag-for "${@}"
    popd >/dev/null
  done
}
