#!/bin/bash

source ~/.bash/functions

if [ -z $RMC_MAX_DEPTH ]; then
  RMC_MAX_DEPTH=3
fi

if [[ -n $1 && "$1" =~ ^[0-9]+$ ]]; then
  RMC_MAX_DEPTH=$1
fi

register_alias rmc "recursive-maven-clean"

function recursive-maven-clean {
  if [ `dirs -p | wc -l` -gt $RMC_MAX_DEPTH ]; then
    return
  fi

  for f in *; do
    if [ -d "$f" ]; then
      pushd "$f" > /dev/null
      if [[ -f "pom.xml" && -d "target" ]]; then
        echo -e "Calling maven clean in folder $(pwd) ..."
        mvn -q clean
      else
        recursive-maven-clean
      fi
      popd > /dev/null
    fi
  done
}
