#!/bin/bash

source ~/.bash/functions

source $(script_path $BASH_SOURCE[0])/prompt.d/utils
source $(script_path $BASH_SOURCE[0])/prompt.d/git-prompt
source $(script_path $BASH_SOURCE[0])/prompt.d/hg-prompt
source $(script_path $BASH_SOURCE[0])/prompt.d/svn-prompt
source $(script_path $BASH_SOURCE[0])/prompt.d/python-virtualenv

__set_prompt() {
    local vcs_pre="$(__git_fetch)"
    local vcs_prompt="$(__git_prompt)$(__hg_prompt)$(__svn_prompt)"
    local virtualenv="$(__pyvenv_prompt)"
    local window_title="\[\e]0;${virtualenv}${current_dir}\a\]"
    PS1="${vcs_pre}${vcs_pre:+"\\n"}${PREFIX}${window_title}${virtualenv}${vcs_prompt}${SUFFIX}\$ "
}

unset PS1
PROMPT_COMMAND=__set_prompt
