#!/bin/bash
source ~/.bash/functions

case $( uname -s ) in
Linux) register_alias ls "ls -a --color";;
Darwin) register_alias ls "ls -aG";;
esac

register_alias rm "rm -i"

register_alias grep "grep --color=auto"
register_alias egrep "egrep --color=auto"
register_alias fgrep "fgrep --color=auto"
