#!/bin/bash

source ~/.bash/functions

case $( uname -s ) in
  Linux)
    register_alias ls "ls -a --color"
    register_alias pbcopy "xsel --clipboard --input"
    register_alias pbpaste "xsel --clipboard --output"
    ;;
  Darwin)
    register_alias ls "ls -aG"
    register_alias show-hidden-files 'defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    register_alias hide-hidden-files 'defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
    ;;
esac

register_alias rm "rm -i"

register_alias grep "grep --color=auto"
register_alias egrep "egrep --color=auto"
register_alias fgrep "fgrep --color=auto"
