#!/bin/bash

source ~/.bash/functions

register_alias ls "ls -aG"
register_alias rm "rm -i"

register_alias grep "grep --color=auto"
register_alias egrep "egrep --color=auto"
register_alias fgrep "fgrep --color=auto"
