#!/bin/bash 

source ~/.bash/functions

local self_dir=$(script_path $BASH_SOURCE[0])
source $self_dir/utils

function __git_prompt {
    git rev-parse --is-inside-work-tree >/dev/null 2>&1 || git rev-parse --is-inside-git-dir >/dev/null 2>&1 || return

    ref=$(git symbolic-ref HEAD 2>/dev/null)
    git_basedir=$(git rev-parse --git-dir)
    branch_name=${ref#refs/heads/}
    if [ "${branch_name}" == "" ]; then
      # detached HEAD
      tag_name=$(git describe --abbrev=0 --exact-match --tags 2>/dev/null)
      if [ "${tag_name}" != "" ]; then
        branch_name="tag @ ${tag_name}"
      else
        branch_name="detached @ $(git rev-parse --short HEAD)"
      fi
    fi
    remote_branch_name="$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)"
    remote_status="${blink}${BIRed}"
    if [ "${remote_branch_name}" == "@{u}" ]; then
      remote_status="${remote_status}⚠ "
      remote_branch_name=""
    fi

    # Based on https://gist.github.com/woods/31967

    # Set color based on clean/staged/dirty
    git_status="$(git status 2> /dev/null)"
    if [[ ${git_status} =~ "working directory clean" || ${git_status} =~ "working tree clean" ]]; then
        state="${Green}"
    elif [[ ${git_status} =~ "Changes to be committed" && ${git_status} =~ "Changes not staged for commit" ]]; then
        state="${Orange}"
    elif [[ ${git_status} =~ "Changes to be committed" ]]; then
        state="${Yellow}"
    else
        state="${Red}"
    fi

    # Set arrow icon based on status against origin.
    if [ "${remote_branch_name}" != "" ]; then
      git_behind="$(git rev-list HEAD..${remote_branch_name} | wc -l | bc)"
      git_ahead="$(git rev-list ${remote_branch_name}..HEAD | wc -l | bc)"

      if [[ "${git_behind}" != "0" ]]; then
          remote_status="${remote_status}↓"
      fi

      if [[ "${git_ahead}" != "0" ]]; then
          remote_status="${remote_status}↑"
      fi
    fi

    remote_status="${remote_status}${Color_Off}"

    printf "${BIWhite}∓ (${state}${branch_name}${remote_status}${BIWhite})${Color_Off} "
}

function __git_fetch {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    git_basedir=$(git rev-parse --git-dir)
    [ ! -f ${git_basedir}/FETCH_HEAD ] && fetch_required=1

    origin_outdated="$(find ${git_basedir}/FETCH_HEAD -mmin +10 2>/dev/null | wc -l | bc)"
    if [[ "${origin_outdated}" == "1" ]]; then
        fetch_required=1
    fi

    if [[ "${fetch_required}" == "1" ]]; then
        echo "Remote information is outdated. Running git fetch."
        git fetch --all
    fi

}
