#!/bin/bash

source ~/.bash/functions

local self_dir=$(script_path $BASH_SOURCE[0])
source $self_dir/utils

function __rbvenv_prompt {
if [[ $(declare -f -F __rvm_env_string) == "__rvm_env_string" ]]; then
    local _ruby_venv_name=$(__rvm_env_string)
    if [[ -n ${_ruby_venv_name} && ${_ruby_venv_name} != "system" ]]; then
        printf "(${_ruby_venv_name}) "
    fi
  fi
}
