#!/bin/bash

reset_color="\[\e[0;0m\]"

red="\[\e[0;31m\]"
green="\[\e[0;32m\]"
yellow="\[\e[0;33m\]"
blue="\[\e[0;34m\]"
cyan="\[\e[0;36m\]"
grey="\[\e[0;37m\]"

light_red="\[\e[1;31m\]"
light_green="\[\e[1;32m\]"
light_yellow="\[\e[1;33m\]"
light_blue="\[\e[1;34m\]"
white="\[\e[1;37m\]"

history_number="\!"
username="\u"
hostname="\h"
current_dir="\w"
current_dir_basename="\W"
