#!/bin/bash

reset_color="\033[0;0m"

red="\033[0;31m"
green="\033[0;32m"
yellow="\033[0;33m"
blue="\033[0;34m"
cyan="\033[0;36m"
grey="\033[0;37m"

light_red="\033[1;31m"
light_green="\033[1;32m"
light_yellow="\033[1;33m"
light_blue="\033[1;34m"
white="\033[1;37m"

history_number="\!"
username="\u"
hostname="\h"
current_dir="\w"
current_dir_basename="\W"
